"""Generate native constant integrity/structure reference from pinned firmware.

Addresses are zeroed in the constants; the native validator supplies current
owned pages. No serialized address supplied by user space becomes authority.
"""
import hashlib
from pathlib import Path
import struct
import prepare_gsp
import gsp_startup

ROOT=Path(__file__).resolve().parent


def generate():
    snapshot=ROOT/'results/gsp-preflight-20260906T122322Z/snapshot.plist'
    if hashlib.sha256(snapshot.read_bytes()).hexdigest()!='384f2c3f3929793525de96e653f8fa5a804928c09de99b6917cb4f4cec20aaf1':
        raise ValueError('Pinned selection evidence changed')
    report,files=prepare_gsp.prepare(ROOT/'firmware/570.144',snapshot)
    pages={}; cursor=0x100000
    for name,row in report['host_resources'].items():
        pages[name]=list(range(cursor,cursor+row['pages']*4096,4096));cursor+=row['pages']*4096
    bound,buffers=prepare_gsp.bind(ROOT/'firmware/570.144',pages,snapshot)
    meta=list(struct.unpack('<32Q',buffers['metadata'][:256]))
    for index in (2,4,9):meta[index]=0
    registry=gsp_startup.encode_registry({'RMForcePcieConfigSave':1,'RMSecBusResetEnable':1})
    text=['#pragma once','// Generated by generate_gsp_seal.py; NVIDIA 570.144, fixed GA106 profile.',
          '// No live addresses. Regenerate only after validating pinned source hashes.','namespace GSPSealConstants {',
          'constexpr unsigned char Registry[] = {'+','.join(str(b) for b in registry)+'};',
          'constexpr unsigned long long Metadata[32] = {'+','.join(hex(x)+'ULL' for x in meta)+'};']
    for name,data in [('Image',files['gsp-fwimage.bin']),('Bootloader',buffers['bootloader']),
                      ('Signature',buffers['signature']),('Booter',buffers['booter_load'])]:
        text.append('constexpr unsigned char '+name+'SHA256[32] = {'+','.join(str(x) for x in hashlib.sha256(data).digest())+'};')
    text.extend(['constexpr unsigned ImageTableBytes = '+str(report['radix_geometry']['table_size'])+';',
                 'constexpr unsigned ImageBytes = '+str(len(files['gsp-fwimage.bin']))+';',
                 '}',''])
    return '\n'.join(text)


if __name__=='__main__':
    path=ROOT/'driver/generated/gsp-seal-constants.hpp'
    path.write_text(generate())
    print(path.name,hashlib.sha256(path.read_bytes()).hexdigest())
